### ISSUE TITLE
URL para consulta de status para Nota de Serviço

### ISSUE THREAD

**Issue by aramisf** [Sage/sageone_br_nfe_documentacao_api#1]
Disponibilizar uma URL na api que permita listar as notas de Serviço (bem como as RPSs) e seus respectivos status.

**Comment by Multnota** [comment]
Caro aramisf. Estou na última etapa de configuração da API mas estou tendo problemas, como faço para entrar em contato contigo ?

**Comment by aramisf** [comment]
Olá @Multnota,

Se sua dificuldade tem relação com este problema ([`URL para consulta de status para Nota de Serviço`](https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/1)) então é aqui mesmo o local. Descreva com o máximo de detalhes o seu contexto, tudo o que você tentou fazer, as URLs que está usando, os parâmetros, e principalmente, as mensagens de erro que estão sendo exibidas.

Agora, se o seu problema não tem relação com **`URL para consulta de status para Nota de Serviço`**, procure nos outros [issues](https://github.com/Sage/sageone_br_nfe_documentacao_api/issues) aqui do repositório e comente no local mais apropriado. Caso nenhum dos [issues](https://github.com/Sage/sageone_br_nfe_documentacao_api/issues) represente com precisão o seu problema, você pode [criar um novo](https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/new).

É interessante deixarmos estas informações públicas para que outras pessoas possam consultar no futuro. Mas se o seu problema envolve exposição de dados pessoais, então você deve entrar em contato direto com o suporte SageOne.
