### ISSUE TITLE
Inclusão de novas cidades

### ISSUE THREAD

**Issue by fabriciosage** [Sage/sageone_br_nfe_documentacao_api#12]
Inclusão de novas cidades: Blumenau, Joinville, Tubarão, Laguna, Palhoça, Itaguaí, Itapecerica da Serra, Taboão da Serra.

**Comment by javacunha** [comment]
Fabricio você conseguiu avançar?

Cheguei até o código e depois todos os métodos dá acesso negado e os métodos alguns métodos que me foram orientados não batem com a documentação.

Estou começando a achar que este sistema não tem api e fico só perdendo meu tempo e dinheiro.

Onde está a documentação que tem os métodos com estes edpoint /notafiscal/v1/nfces/authorize
O que toda hora me encaminham para este endereço https://developers.sageone.com/docs/en/v1 só tem /accounts/v1/ ...

**Comment by Tarcisiosk** [comment]
Olá @javacunha  você pode verificar os endpoints e maiores informações em: https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki

Se você obtiver algum problema, por gentileza, descreva os passos realizados com o maior detalhamento possível. Obrigado!

Att. Tarcisio Skora
