### ISSUE TITLE
Correção layout NF

### ISSUE THREAD

**Issue by orcacontrol** [Sage/sageone_br_nfe_documentacao_api#13]
Solicito a correção dos nomes dos campos para importação e geração das notas fiscais na API.
Segue abaixo o link do modelo atual.
https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe

**Comment by javacunha** [comment]
Orcacontrol você conseguiu avançar?

Cheguei até o código e depois todos os métodos dá acesso negado e os métodos alguns métodos que me foram orientados não batem com a documentação.

Estou começando a achar que este sistema não tem api e fico só perdendo meu tempo e dinheiro.

Onde está a documentação que tem os métodos com estes edpoint /notafiscal/v1/nfces/authorize
O que toda hora me encaminham para este endereço https://developers.sageone.com/docs/en/v1 só tem /accounts/v1/ ...

**Comment by Tarcisiosk** [comment]
Olá @orcacontrol, desculpe mas não conseguimos identificar o erro, poderia informar o erro que está tendo com os nomes dos campos?

Att. Tarcisio Skora

**Comment by Tarcisiosk** [comment]
Fechando esse tópico por inatividade.
