### ISSUE TITLE
URL para endpoint?

### ISSUE THREAD

**Issue by brnmonteiro** [Sage/sageone_br_nfe_documentacao_api#14]
Afina, qual a url utilizada para o endpoint no BR? app.br.sageone.com ou api.sageone.com ? quando utilizo do app.br da internal error...

o code é obtido por app.br? e o access token também?

**Comment by felipe-ohira** [comment]
Também estou com esse problema

Quando faço uma requisição para o ```https://api.sageone.com/notafiscal/api/v1/issuer.sdata``` ao invés de retornar os dados da empresa que cadastrei, o retorno é:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>The page you were looking for doesn't exist (404)</title>
        <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
    </head>
    <body>
        <!-- This file lives in public/404.html -->
        <div class="dialog">
            <h1>The page you were looking for doesn't exist.</h1>
            <p>You may have mistyped the address or the page may have moved.</p>
        </div>
    </body>
</html>
```

Qual o endereço correto da API BR?

**Comment by MatheusNaida** [comment]
Está errado na documentação. Eu consegui usando essa url:
https://api.sageone.com/notafiscal/v1/issuer.sdata

Sem o /api

**Comment by luizhpcamargo** [comment]
Obrigado pela observação @MatheusNaida, já efetuamos a correção na wiki
