### ISSUE TITLE
Serviços não encontrados para NFCe

### ISSUE THREAD

**Issue by douglassmartwaiter** [Sage/sageone_br_nfe_documentacao_api#17]
Olá não encontrei na documentação serviços para:

1- Autorizar a NFCe, vi que tem um para NFSe e para NFe (/notafiscal/v1/nfes/authorize)
      Dúvida: o servico /notafiscal/v1/nfces/new apenas cria a nota no sage, correto?

2- Listar a DANFE

3- Enviar DANFE via e-mail

Estou abrindo issue, pois fui informado no suporte do officeservice que esse seria o local para
esse tipo de pergunta.

**Comment by luizhpcamargo** [comment]
1- Para NFCe seria o mesmo meio o /notafiscal/v1/nfces/authorize, sim o new somente cria a nota.

2- a DANFE só pode ser visualizada por dentro do Sage One

3- a DANFE é enviada por e-mail após a emissão da nota.

**Comment by douglassmartwaiter** [comment]
Preciso imprimir a DANFE no PDV, alguma outra alternativa?

**Comment by douglassmartwaiter** [comment]
Nao preciso do retorno da danfe em HTML, pode ser JSON, algum retorno?

**Comment by luizhpcamargo** [comment]
Olá, estamos em estudo para colocar essa nova funcionalidade. Não a possuimos ainda

**Comment by javacunha** [comment]
Douglas você conseguiu avançar?

Cheguei até o código e depois todos os métodos dá acesso negado e os métodos alguns métodos que me foram orientados não batem com a documentação.

Estou começando a achar que este sistema não tem api e fico só perdendo meu tempo e dinheiro.

Onde está a documentação que tem os métodos com estes edpoint /notafiscal/v1/nfces/authorize
O que toda hora me encaminham para este endereço https://developers.sageone.com/docs/en/v1 só tem /accounts/v1/ ...

**Comment by Tarcisiosk** [comment]
Olá @douglassmartwaiter a requisição para sua sugestão foi criada e será desenvolvida quando estabelecida pelo nosso PO.
https://jira-sage.valiantyscloud.net/browse/SB-1336
Att. Tarcisio Skora
