### ISSUE TITLE
Como faço para pegar a autorização no desenvolvimento?

### ISSUE THREAD

**Issue by javacunha** [Sage/sageone_br_nfe_documentacao_api#18]
Consegui pegar o code para geração do token para trabalhar, porém tive que colocar na internet uma página para pegar o código.

Como fazer isso no ambiente de desenvolvimento? No localhost.

**Comment by javacunha** [comment]
E como fazer

**Comment by javacunha** [comment]
desculpe. Pode fechar.

**Comment by luizhpcamargo** [comment]
sem problemas ;)
