### ISSUE TITLE
Erro ao solicitar o token

### ISSUE THREAD

**Issue by javacunha** [Sage/sageone_br_nfe_documentacao_api#20]
Ao chamar a urlWebService via post e enviando os parametros lança o seguinte erro:

urlWebService: https://api.sageone.com/oauth2/token
parametros: client_id=xxxx&client_secret=xxxx&code=ce0074e0901884cc6201eb52d93017438c0bee7b&grant_type=authorization_code&redirect_uri=https://app.sisdanca.com.br/sistema/sageone/calback.jsp

Erro:
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sageone.com/oauth2/token
Erro na integração de conta: {"error":"invalid_grant"}

Obs: Já tentei os 02 valores: grant_type - The type of grant the code relates to. Either authorization_code or refresh_token.

**Comment by luizhpcamargo** [comment]
O método deve ser um post, como você está enviando? Está utilizando alguma lib para fazer a conexão OAuth?

**Comment by javacunha** [comment]
Estou enviando assim:

            URL url = new URL(urlWebService);
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setDoOutput(true);
            connection.setConnectTimeout(15000);
                       
            DataOutputStream stream = new DataOutputStream(connection.getOutputStream());
            stream.write( parametros.getBytes("UTF-8") );
            stream.flush();
            stream.close();
            connection.connect();

            String responseJson = inputStreamToString(connection.getInputStream());

**Comment by javacunha** [comment]
E então pessoal? Continuo com o problema. Alguma sugestão?

**Comment by javacunha** [comment]
O problema era com as libs que estavam sendo usadas. Tudo resolvido deste tópico.
