### ISSUE TITLE
Configuração API

### ISSUE THREAD

**Issue by Multnota** [Sage/sageone_br_nfe_documentacao_api#21]
Prezado(s), boa tarde,

Estou com dificuldade para implementar a API. Estou utilizando a biblioteca PHP, mas ao receber o token de autorização da uma página inválida ?

**Comment by luizhpcamargo** [comment]
Bom dia 👍 
o callback é criado por você, o importante para o funcionamento da API é o code que ele retornar.
Com ele você requisita o token de acesso e começa a utilizar os verbos da API.

Obrigado pelo contato

**Comment by Multnota** [comment]
luizhpcamargo já estou com o code de retorno da API. Tenho os seguintes arquivos nesta biblioteca. https://github.com/Sage/sageone_api_php_sample  Qual é o passo seguinte ?
