### ISSUE TITLE
Erro ao obter token  getToken($params) 

### ISSUE THREAD

**Issue by Multnota** [Sage/sageone_br_nfe_documentacao_api#23]
Warning: file_get_contents(https://api.sageone.com/oauth2/token) [function.file-get-contents]: failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /home/storage/5/41/b2/totalnota/public_html/app/sageone_client.php on line 128
bool(false). 

Os parâmetros estão exatamente nesta sequência.

**Context:** 
resource(3) of type (stream-context) 

**Options:**
array(1) { ["http"]=> array(3) { ["header"]=> string(49) "Content-type: application/x-www-form-urlencoded " ["method"]=> string(4) "POST" ["content"]=> string(229) "client_id=37ac237c40_**&client_secret=__033032725e_**&code=**b4372dc6b42be0a288***&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fwww.totalnota.com.br%2Fapp%2Fcallback%2F" } } 

**Params:** 
array(5) { ["client_id"]=> string(20) "37ac237c405da02a1368" ["client_secret"]=> string(40) "*_**f939aa5b32a1__" ["code"]=> string(40) "_**" ["grant_type"]=> string(18) "authorization_code" ["redirect_uri"]=> string(42) "https://www.totalnota.com.br/app/callback/" }

**Comment by luizhpcamargo** [comment]
Como vocês está implementando o acesso OAuth2?

**Comment by Multnota** [comment]
Estamos implementando utilizando esta sample: https://github.com/Sage/sageone_api_php_sample . Já consegui o code mas ao obter o token ele da esse erro...

**Comment by Multnota** [comment]
Acesso OAuth2:

private $oAuthAuthoriseURL = 'https://www.sageone.com/oauth2/auth';
private $oAuthAccessTokenURL = 'https://api.sageone.com/oauth2/token';
private $apiUrl = 'https://api.sageone.com';

Estou achando que pode ser algum erro de autorização com o certificado.

Erro ao tentar uma call com **oauth**: string(35) "{"error":"unsupported_grant_type"} " int(0) 

Erro ao tentar uma call com **post**: string(114) "{"$diagnoses":[{"$severity":"error","$dataCode":"AuthorizationFailure","$message":"Access Denied","$source":""}]} " int(0)

**Comment by Multnota** [comment]
Será que tem a ver com o certificado A1 do cliente ?

**Comment by Tarcisiosk** [comment]
Olá @Multnota, o erro unsupported_grant_type acontece quanto não está sendo enviado o token corretamente você pode verificar mais detalhes na documentação: https://developers.sageone.com/docs/en/v1

Vale lembrar que o erro acontece porque não foi informado o `authorization_code` ou o `refresh_token`. O `authorization_code` é utilizado para conseguir o `access_token`, quando ele expirar o `refresh_token` é utilizado para conseguir um novo.

Att. Tarcisio Skora
