### ISSUE TITLE
Erro ao solicitar token de acesso

### ISSUE THREAD

**Issue by Multnota** [Sage/sageone_br_nfe_documentacao_api#24]
Boa tarde, não estou conseguindo solicitar o token de acesso ? getToken();. O meu código de cliente é o: 93419-02.  O erro que recebemos é o.

failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /home/storage/5/41/b2/totalnota/public_html/app/sageone_client.php on line 123.

Existe algum local para contato telefônico sobre dúvidas de desenvolvedores ?

**Comment by luizhpcamargo** [comment]
Olá, n temos contato direto. Vou tentar ver alguém aqui para ajudar a solucionar o problema.
Você está utilizando alguma biblioteca OAuth2?

**Comment by Multnota** [comment]
Estou utilizando a biblioteca PHP.

**Comment by Multnota** [comment]
Alguém ?

**Comment by luizhpcamargo** [comment]
Desculpe toda a demora =) Você consegue algum retorno positivo? ou isso é até onde foi baseado no código?

**Comment by Multnota** [comment]
Exatamente parei nessa parte. Só precisamos do token de acesso, sem ele não consigo prosseguir. A minha dúvida é se essa negação tem alguma relação com o certificado A1 dele ?

**Comment by luizhpcamargo** [comment]
Você chegou até a parte q retorna o code?

**Comment by fxneel** [comment]
Sim

**Comment by javacunha** [comment]
Djalma, você conseguiu avançar?

Cheguei até o código e depois todos os métodos dá acesso negado e os métodos alguns métodos que me foram orientados não batem com a documentação.

Estou começando a achar que este sistema não tem api e fico só perdendo meu tempo e dinheiro.

**Comment by Multnota** [comment]
Nada... eu desistir falei com o cliente que não vale a dor de cabeça. Documentação está incompleta o suporte para desenvolvedores fraquíssimo levam uma eternidade para responder e não passam nenhuma informação precisa, sinceramente não recomendo adquirir a API do SageOne.

**Comment by GeovaneHiMaker** [comment]
Estou com o mesmo problema e não conseguir prosseguir, até gerar o code é tranquilo, depois vc fica preso.
alguém pode ajudar?

**Comment by Tarcisiosk** [comment]
Olá você pode tentar as soluções: 
https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/23
https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/20

Caso ainda não consiga, por gentileza abrir um issue com mais detalhes das tentativas de acesso
