### ISSUE TITLE
Requisição retorna 500 ao tentar criar uma Nota fiscal de serviço

### ISSUE THREAD

**Issue by WilliamFM-mrprint** [Sage/sageone_br_nfe_documentacao_api#25]
Boa tarde, 

Estou tentando usar a API para criar uma nota fiscal de serviço. Estou seguindo a documentação contida em: https://developers.sageone.com/docs/en/v1,  e o modelo de código do link: https://github.com/Sage/sageone_api_php_sample.
A requisição me retorna 200 quando envio para test/notafiscal/v1/rpss/new. Entretanto ao tentar enviar para notafiscal/v1/rpss/new eu recebo o código 500 do HTTP, e uma pagina de "Ocorreu um erro".

**Comment by luciano-mrprint** [comment]
Nunca vimos um suporte tão ruim quanto o da Sage. Misericórdia. Deviam ter ficado só no exterior porque aqui no Brasil vocês não estão conseguindo fazer um bom trabalho. Para que oferecem uma API se não tem uma documentação adequada e pessoas qualificadas para darem suporte? Enviamos e-mail e demoram 1 semana para responderem e respondem com um link que não está com o conteúdo atualizado. Abrimos um issue e fica por dias sem uma resposta. Esta não é uma solução séria. Sinto muito, vocês tem muito o que fazer para serem péssimos.

**Comment by luizhpcamargo** [comment]
Boa noite,
Como vc está tratando a autenticação?

**Comment by Tarcisiosk** [comment]
Topico fechado por inatividade.
