### ISSUE TITLE
Atualização dos dados do Cliente

### ISSUE THREAD

**Issue by MAPDataTI** [Sage/sageone_br_nfe_documentacao_api#29]
Boa tarde!

Quando crio uma NFE através da API, envio os dados do cliente. Porém percebi que caso o cliente já exista, os dados do cliente não são atualizados.
E o DANFE é gerado com os dados desatualizados do cliente.

Como devo proceder para forçar a atualização dos dados cadastrais do cliente?

Obrigado!

**Comment by mandakeru** [comment]
Boa tarde, ao passar os atributos do cliente o sistema não atualiza o mesmo.
Outros usuarios ja pediram essa funcionalidade e ela será implementada em releases futuras.
O comportamento da API e apenas cadastrar se o cliente não existir, se existir(baseado no CPF) ela apenas usa o cliente para a ação desejada e não atualiza os dados do mesmo.

**Comment by MAPDataTI** [comment]
A checagem de existência leva em consideração o tipo de pessoa? Se pessoa física usa CPF e se pessoa jurídica CNPJ?

Obrigado!

**Comment by MAPDataTI** [comment]
A checagem de existência leva em consideração o tipo de pessoa? Se pessoa física usa CPF e se pessoa jurídica CNPJ?

Aguardando resposta...

**Comment by Tarcisiosk** [comment]
Olá @MAPDataTI a checagem verifica de acordo com o tipo de pessoa, caso seja pessoa física verifica-se o CPF, caso jurídica o CNPJ.
