### ISSUE TITLE
Erro ao Incluir NFE

### ISSUE THREAD

**Issue by MAPDataTI** [Sage/sageone_br_nfe_documentacao_api#30]
Boa tarde!
Estou tentando gerar uma NFE através da url (https://api.sageone.com/notafiscal/v1/nfes/new) porém o sistema não está permitindo executar a operação devido ao uso do caractere de parênteses na descrição do produto. Se eu removo os parênteses da descrição, funciona normalmente.
Existe alguma recomendação para esta situação?
Grato e no aguardo,
Antonio Chiachio
MAPData Tecnologia.

**Comment by mandakeru** [comment]
Olá bom dia Antonio,
Verifique se está usando corretamente as aspas, pois a descrição é uma string, logo tudo que tiver dentro das aspas incluindo parênteses é reconhecido pelo sistema.

**Comment by MAPDataTI** [comment]
Olá Jean, bom dia!
Usei como base o exemplo existente de vocês. No exemplo os dados são montados como na linha de código a seguir:
`postData.Add(new KeyValuePair<string, string>("items[0][product][name]", "Teste"));`

Desta forma FUNCIONA, mas se a informação estiver assim:

`postData.Add(new KeyValuePair<string, string>("items[0][product][name]", "Teste (teste)"));`

NÃO FUNCIONA!

Obs.: O desenvolvimento é em C#.

Grato e no aguardo,
Antonio Chiachio
MAPData Tecnologia

**Comment by Tarcisiosk** [comment]
Olá @MAPDataTI poderia tentar realizar a chamada:
postData.Add(new KeyValuePair<string, string>("items[0][product][name]", @"Teste (teste)"));

Att. Tarcisio Skora

**Comment by MAPDataTI** [comment]
Olá, boa tarde!
Informo que efetuei um teste com a sugestão apresentada, porém o problema persiste.
Grato e no aguardo,
Antonio Chiachio
MAPData Tecnologia

**Comment by Tarcisiosk** [comment]
Olá, @MAPDataTI  você poderia nos informar qual a mensagem de erro que está aparecendo?

**Comment by MAPDataTI** [comment]
Olá @Tarcisiosk,
Pelo meu rastreamento a mensagem que estou recebendo é essa:
`{"$diagnoses":[{"$severity":"error","$dataCode":"AuthorizationFailure","$message":"Access Denied","$source":""}]}`
Porém se retiro o parênteses da descrição do produto, o problema não ocorre e a nota é inserida normalmente.

Atenciosamente,
Antonio Chiachio
MAPData Tecnologia

**Comment by MAPDataTI** [comment]
@Tarcisiosk, boa tarde!

Alguma novidade?

Obrigado!
Antonio Chiachio
MAPData Tecnologia

**Comment by raphaelnm** [comment]
Também estou tendo dificuldades com esse endpoint.
Entre outros, envio os seguintes dados:

`'client[icms_contributor]' => 0,`
`'client[tax_number]' => 'ISENTO',`
`'client[address][city_ibge_code]' => 3545001,`

Aparentemente o cliente é cadastrado corretamente.

![cliente](https://cloud.githubusercontent.com/assets/10108308/23913597/41200158-08c2-11e7-9652-09668a5d4b77.png)

Quando emito a NFe ocorrem os erros abaixo:

![screen shot 2017-03-14 at 14 28 12](https://cloud.githubusercontent.com/assets/10108308/23913704/83e779bc-08c2-11e7-8319-ace44c96a250.png)

Tentei enviar o seguinte dado, também:

`'client[address][uf]' => 'SP',`

Nesse caso a API retorna erro interno (500).

**Comment by mandakeru** [comment]
Olá bom dia, os erros apresentados são referentes aos dados de sua empresa, poderia verificar se preencheu corretamente? Quando da erro referente ao cliente as mensagens de erro citam o cliente.

**Comment by raphaelnm** [comment]
Bom dia @mandakeru 
Essa é a configuração da empresa, que eu utilizo há meses. Os dados citados no erro estão preenchidos.

![configuracao_empresa](https://cloud.githubusercontent.com/assets/10108308/23948925/fc9b7f42-0963-11e7-8221-66956aa7fb9f.png)

Depois de ler seu comentário, encontrei e preenchi o quadro abaixo:

![configuracao_empresa2](https://cloud.githubusercontent.com/assets/10108308/23948959/12894f28-0964-11e7-87f0-fdcadc1fad17.png)

E o resultado foi exatamente o mesmo.

Existe alguma outra configuração?

**Comment by mandakeru** [comment]
@raphaelnm existem alguns estados que a Inscrição estadual do cliente não pode ser isento, voce esta passando todas as informações do cliente na chamada ou somente seu id?

**Comment by raphaelnm** [comment]
@mandakeru estou passando os seguintes dados:

```
'document'                        => 'AAAAAAAA',
'notes'                           => '',
'expedited_at'                    => Carbon::now()->toIso8601String(), // ISO-8601 format
'nature'                          => 'Venda',
'carriage_modality'               => '9',
'client[kind]'                    => 'person', // person | organization
'client[name]'                    => $owner->name,
'client[legal_name]'              => '',
'client[cpf]'                     => $owner->cpf,
'client[cnpj]'                    => '',
'client[email]'                   => '',
'client[telephone]'               => '',
'client[icms_contributor]'        => 0,
'client[tax_number]'              => 'ISENTO',
'client[address][postal_code]'    => $address->cep,
'client[address][street]'         => $address->address,
'client[address][number]'         => $address->number,
'client[address][complement]'     => $address->complement,
'client[address][neighborhood]'   => $address->district,
'client[address][city_ibge_code]' => $address->ibge_code,
'carrier[name]'                   => 'Correios',
'carrier[cnpj]'                   => '034028316000103',
'items[0][quantity]'              => 1,
'items[0][price]'                 => '19.90',
'items[0][discount]'              => 0,
'items[0][product][code]'         => 1005,
'items[0][product][name]'         => $product->name,
'items[0][product][unit]'         => 'pc',
'items[0][product][barcode]'      => '',
'items[0][product][price]'        => '19.90',
```

**Comment by mandakeru** [comment]
Olá @raphaelnm poderia verificar se as variáveis com o cep estão de fato preenchidas nos momento do envio? pois elas estão indo vazias para a API, verifique também o CPF pois se ele não estiver correto pode dar conflito com o tax_number.

**Comment by raphaelnm** [comment]
@mandakeru eu confirmei os dados de saída no meu log. Os dados estão devidamente preenchidos e enviados para o Sage. 
Eu também fiz um teste alterando valores de saída e o rascunho criado no Sage One continha os novos valores, conforme esperado. Portanto, os dados estão sendo enviados pelo meu sistema e recebidos pelo Sage.

**Comment by Tarcisiosk** [comment]
Resolvido https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/35
