### ISSUE TITLE
Código NCM

### ISSUE THREAD

**Issue by MAPDataTI** [Sage/sageone_br_nfe_documentacao_api#31]
Boa tarde!
Existe na API o campo para código NCM para os produtos?

Obrigado,
Antonio Chiachio
MAPData Tecnologia

**Comment by mandakeru** [comment]
Bom dia,

Sim, existe o campo para o código NCM.
segue a lista dos códigos aceitos:

"00000000","Sem Classificação no NCM"
"0101","Análise e desenvolvimento de sistemas."
"01012100","Cavalos reprodutores,de raca pura"
"01012900","Cavalos vivos,exceto reprodutores de raca pura"
"01013000","Asininos"
"01019000","Outros asininos e muares,vivos"
"0102","Programação."
"01022110","Bovinos reprodutores,de raca pura,prenhe ou com cria ao pe"
"01022190","Outros bovinos reprodutores,de raca pura"
"01022911","Outros bovinos para reprodução, prenhe ou com cria ao pe"
"01022919","Outros bovinos domésticos para reprodução"
"01022990","Outros bovinos domésticos"
"01023110","Búfalos reprodutores,de raca pura, prenhe ou com cria ao pe"
"01023190","Outros búfalos reprodutores,de raca pura"
"01023911","Outros búfalos para reprodução, prenhe ou com cria ao pe"
"01023919","Outros búfalos para reprodução"
"01023990","Outros búfalos"
"01029000","Outros animais vivos da espécie bovina"
"0103","Processamento de dados e congêneres."
"01031000","Suinos  reprodutores de raça pura"
"01039100","Outros suinos,vivos,de peso inferior a 50kg"
"01039200","Outros suinos,vivos,de peso igual ou superior a 50kg"
"0104","Elaboração de programas de computadores, inclusive de jogos eletrônicos."
"01041011","Ovinos reprodutores,de raca pura,prenhe ou c/cria ao pe"
"01041019","Outros ovinos,reprodutores,de raca pura"
"01041090","Outros ovinos,vivos"
"01042010","Caprinos reprodutores,de raca pura"
"01042090","Outros caprinos,vivos"
"0105","Licenciamento ou cessão de direito de uso de programas de computação."
"01051110",
"01051190","Outros galos e galinhas,vivos,de peso n/superior a 185g"
"01051200","Peruas e perus,vivos,de peso nao superior a 185g"
"01051300",
"01051400",
"01051500",
"01059400","Outros galos e galinhas,vivos de peso>185g"
"01059900","Patos,gansos,perus,peruas,pintadas,vivos,de peso>185g"
"0106","Assessoria e consultoria em informática."
"01061100","Primatas"
"01061200","Baleias, golfinhos e botos, peixes-boi e digongos, otárias e focas, leões-marinhos e morsas"
"01061300","Camelos e outros camelídeos"
"01061400","Coelhos e lebres"
"01061900","Outros animais mamíferos"
"01062000","Répteis incluídas as serpentes e as tartarugas marinhas"
"01063100","Aves de rapina"
"01063200","Psitaciformes (incluídos os papagaios, os periquitos, as araras e as cacatuas)"
"01063310","Avestruzes para reprodução"
"01063390","Outros avestruzes, emus"
"01063900","Outras aves"
"01064100","Abelhas"
"01064900","Outro insetos"
"01069000","Outros animais vivos"
"0107","Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."
"0108","Planejamento, confecção, manutenção e atualização de páginas eletrônicas."
"0201","Serviços de pesquisas e desenvolvimento de qualquer natureza."
"02011000","Carcacas e meias carcacas,de bovino,frescas ou refriger"
"02012010","Quartos dianteiros,de bovino,n/desossad. frescos/refrig."
"02012020","Quartos traseiros,de bovino,n/desossados, frescos/refrig"
"02012090","Outs.carnes de bovino,nao desossadas, frescas ou refrig."
"02013000","Carnes de bovino,desossadas,frescas ou refrigeradas"
"02021000","Carcacas e meias-carcacas,de bovino, congeladas"
"02022010","Quartos dianteiros,de bovino,nao desossados, congelados"
"02022020","Quartos traseiros,de bovino,nao desossados, congelados"
"02022090","Outras carnes de bovino,nao desossadas, congeladas"
"02023000","Carnes de bovino,desossadas,congeladas"
"02031100","Carcacas e meias-carcacas,de suino,frescas ou refriger."
"02031200","Pernas,pas,etc.de suino,n/desossados,frescos ou refrig."
"02031900","Outras carnes,de suino,frescas ou refrigeradas"
"02032100","Carcacas e meias-carcacas,de suino, congeladas"
"02032200","Pernas,pas e pedacos,de suinos,n/desossados, congelados"
"02032900","Outras carnes,de suino,congeladas"
"02041000","Carcacas e meias-carcacas,de cordeiro, frescas ou refrig"
"02042100","Carcacas e meias-carcacas,de ovino,frescas ou refriger."
"02042200","Outras carnes,de ovino,nao desossadas, ]frescas ou refrig"
"02042300","Carnes de ovino,desossadas,frescas ou refrigeradas"
"02043000","Carcacas e meias-carcacas,de cordeiro, congeladas"
"02044100","Carcacas e meias-carcacas,de ovino, congeladas"
"02044200","Outras carnes de ovino,nao desossadas, congeladas"
"02044300","Carnes de ovino,desossadas,congeladas"
"02045000","Carnes de caprino,frescas,refrigeradas ou congeladas"
"02050000","Carnes de cavalo,asinino e muar,frescas, refrig.ou cong."
"02061000","Miudezas comestiveis,de bovino,frescas ou refrigeradas"
"02062100","Linguas de bovino,congeladas"
"02062200","Figados de bovino,congelados"
"02062910","Rabos de bovino,congelados"
"02062990","Outras miudezas comestiveis,de bovino, congeladas"
"02063000","Miudezas comestiveis,de suino,frescas ou refrigeradas"
"02064100","Figados de suino,congelados"
"02064900","Outras miudezas,comestiveis,de suino, congeladas"
"02068000","Miudezas comestiveis,de ovino,etc. frescas/refrigeradas"
"02069000","Miudezas comestiveis,de ovino,caprino, etc.congeladas"
"02071100","Carnes de galos/galinhas,n/cort.pedacos, frescas/refrig."
"02071200","Carnes de galos/galinhas,n/cortadas em pedacos,congel."
"02071300","Pedacos e miudezas,de galos/galinhas, frescos/refriger."
"02071400","Pedacos e miudezas,comest.de galos/galinhas, congelados"
"02072400","Carnes de peruas/perus,n/cort.pedacos, frescas/refriger."
"02072500","Carnes de peruas/perus,n/cortadas em pedacos,congeladas"
"02072600","Carnes de peruas/perus,em pedacos,miudez. frescos/refrig"
"02072700","Carnes de peruas/perus,em pedacos e miudezas,congeladas"
"02074100","Carnes de patos, n/cort.em pedacos, frescas/refriger."
"02074200","Carnes de patos,gansos,etc.n/cort.em pedacos,congeladas"
"02074300","Figados gordos,de patos (foie gras), frescos/refrig."
"02074400","Outs.carnes/miudezas,de patos,frescas, refrig"
"02074500","Outs.carnes,miudezas,de patos, congeladas"
"02075100","Carnes de gansos n/cort.em pedacos, frescas/refriger."
"02075200","Carnes de  gansos n/cort.em pedacos,congeladas"
"02075300","Figados gordos,de gansos (foie gras), frescos/ refrig."
"02075400","Outs.carnes/miudezas,de gansos, frescas, refrig"
"02075500","Outs.carnes,miudezas,de gansos, congeladas"
"02076000","Carnes e miudezas comestíveis de galinhas dangola (pintadas), frescas/refriger/ congeladas"
"02081000","Carnes/miudezas,de coelhos/lebres,frescas/ refrig/congel"
"02083000","Carnes e miudezas,de primatas,frescos/ refrig/congel"
"02084000","Carnes e miudezas,de baleias,golfinhos e botos, peixes-boi e digongos, otárias e focas, leões-marinhos e morsas ,frescos/ refrig/ congel"
"02085000","Carnes e miudezas,de répteis(incluidas as serpentes e as tartarugas marinhas), frescos/ refrig/congel"
"02086000","Carnes e miudezas,de camelos e outros camelídeos, frescos/ refrig/congel"
"02089000","Carnes e miudezas,de outs.animais,frescos/ refrig/congel"
"02091011","Toucinho de porco sem partes magras, fresco/ refrigerado/ congelado"
"02091019","Toucinho sem partes magras,salgado/ salmoura/ seco/defum."
"02091021","Gordura de porco,fresca,refrigerada ou congelada"
"02091029","Gordura de porco,n/fundida,salgada,em salmoura,seca,etc"
"02099000","Gordura de aves,n/fundida,fresca, refrigerada,congel.etc"
"02101100","Pernas/pas/pedacos,de suino,n/desossados, salgados,etc."
"02101200","Barrigas e peitos,entremeados,de suino,salgados,etc."
"02101900","Outs.carnes de suino,salgadas ou em salmoura,secas,etc."
"02102000","Carnes de bovinos,salgadas/em salmoura/ secas/defumadas"
"02109100","Carnes e miudezas,de primatas,salgados,etc."
"02109100","Miudezas, farinhas e pós dessas miudezas de primatas"
"02109200","Carnes e miudezas,de baleias,golfinhos e botos, peixes-boi e digongos, otárias e focas, leões-marinhos e morsas,salgados,etc."
"02109200","Miudezas, farinhas e pós dessas miudezas de baleias, golfinhos e botos  mamíferos da ordem dos cetáceos , de peixes-boi  manatins  e dugongos  mamíferos da ordem dos sirênios , de otárias e focas, leões-marinhos e morsas  mamíferos da subordem dos pinípedes "
"02109300","Carnes e miudezas,de répteis(incluidas as serpentes e as tartarugas marinhas), salgados,etc."
"02109300","Miudezas, farinhas e pós dessas miudezas de répteis  incluindo as serpentes e as tartarugas marinhas "
"02109900","Carnes e miudezas,de outros animais,salgados, etc."
"02109900","Miudezas, exceto fígados de aves da posição 01.05, farinhas e pós dessas miudezas"
"02109900","Fígados de aves da posição 01.05, salgados ou em salmora"
"0301","Vetado"
"03011110","Aruanã (peixe ornamental)"
"03011190","Outros peixes ornamentais, vivos,  de água doce"
"03011900","Outros peixes ornamentais vivos"
"03019110","Trutas (salmo trutta e oncorhynchus),para reproducao"
"03019190","Outros trutas (salmo trutta e oncorhynchus),vivas"
"03019210","Enguias (anguilla spp.) para reproducao"
"03019290","Outros enguias (anguilla spp.) vivas"
"03019310","Carpas para reproducao"
"03019390","Outros carpas vivas"
"03019410","Atuns-azuis (thunnus thynnus, thunnus orientalis) para reprodução"
"03019490","Outros atuns-azuis (thunnus thynnus, thunnus orientalis)"
"03019510","Atuns-do-sul (thunnus maccoyii) para reprodução"
"03019590","Outros  atuns-do-sul (thunnus maccoyii)"
"03019911","Tilapias,peixes para reproducao"
"03019912","Esturjões,peixes para reproducao"
"03019919","Outros peixes vivos para reprodução"
"03019991","Tilapias,peixes vivos"
"03019992","Esturjões,peixes vivos"
"03019999","Outros peixes vivos"
"0302","Cessão de direito de uso de marcas e de sinais de propaganda."
"03021100","Trutas frescas,refrig.exc.files,outs. carnes, figados,etc"
"03021300","Salmoes-do-pacifico, frescos,refrig. exc.files,etc."
"03021400","Salmoes-do-atlantico, frescos,refrig. e...

**Comment by MAPDataTI** [comment]
Bom dia @mandakeru !

Mas como é o nome do campo? Por exemplo, para unidade usamos:

`'items[1][product][unit]' = 'kg'`

NCM seria:

`'items[1][product][ncm]' = '123456'`

Obrigado,
Antonio Chiachio
MAPData Tecnologia

**Comment by Tarcisiosk** [comment]
Olá @MAPDataTI, desculpe pela demora em respondê-lo, houve uma grande mudança no nosso time de desenvolvimento e estamos colocando as coisas no lugar. 
'items[1][product][ncm]' = '123456' essa é a maneira correta mesmo.
