### ISSUE TITLE
Dúvidas de iniciante

### ISSUE THREAD

**Issue by rolembergfilho** [Sage/sageone_br_nfe_documentacao_api#32]
Prezados,

Estou analisando a adoção da ferrramenta SAGEONE como emissor de NFSe.

Para tanto, tenho as seguintes dúvidas:

1 - Qual a diferença entre criar nova NFSe e criar e autorizar nova NFSe (há dois exemplos dissos na documentação da SageOne)

2 - Há algum exemplo de como excluir NFSe? Caso negativo, qual é o processo para excluir uma NFSe?

3 - Vi em alguns chamados antigos que quando criar uma nova NFSe, e o cliente já existir no banco de dados da Sage, serão utilizados os dados pré-existentes... Face a essa realidade, como atualizar os dados do cliente **antes** de criar uma nova NFSe? Há alguma api para isso?

4 - Tenho certificado A3. Como utilizar na API da SageOne?

**Comment by GeovaneHiMaker** [comment]
"Nova NFSe" é em ambiente de homologação, sem valor fiscal;
"Autorizar Nova NFSe" é em ambiente de produção, com valor fiscal.
(posso estar errado)

**Comment by rolembergfilho** [comment]
Obrigado  Geovane,

Pelo que entendi, você é usuário da SageOne.

Li nos posts mais antigos que os usuários reclamam bastante do suporte provido para API. O que você tem achado? conseguiu integrar seu sistema de um jeito satisfatório com a API da SageOne?

**Comment by GeovaneHiMaker** [comment]
De nada,
Não, não consigo contatar eles direito para tirar minhas duvidas e estou estou com problemas para gerar o token, você teve algum progresso sobre isso?

**Comment by rolembergfilho** [comment]
Não tive problemas ainda, pois ainda nem assinei com a SageOne.

Estou em negociação já tem um tempinho, achei o valor competitivo. Mas achei que a documentação deveria ser melhor trabalhada, e um suporte mais robusto deveria ser providenciado!

O bom desse site é que são desenvolvedores interessados em fazer o sistema funcionar. Com isso, não sei se falta boa vontade ou simplesmente uma reorganização por parte da SageOne para fazer valer quem realmente interessa: os desenvolvedores de soluções para seus clientes!

**Comment by rolembergfilho** [comment]
Um complemento: acredito que a equipe de TI deve ser competente, pois uma empresa multinacional britânica não arriscaria criar uma subsidiária no Brasil, prover produtos defeituosos, induzir diversos clientes ao erro e levar uma multa da Receita, fora processos por parte dos clientes.

Face a essa situação, procuro entender o motivo dessa lacuna quanto ao suporte da SageOne

**Comment by rolembergfilho** [comment]
a quem se interessar, usei os fontes da UniMake.

infelizmente a Sage não me satisfez, devido à lentidão da equipe de suporte....
