### ISSUE TITLE
invalid_grant ao tentar gerar o Access Token

### ISSUE THREAD

**Issue by rodrigoamuchastegui** [Sage/sageone_br_nfe_documentacao_api#33]
Estou usando o exemplo em C# para implementar a API em meu sistema de gestão.
Eu consegui gerar o Authorization Code normalmente, porém, ao tentar gerar o Access Token, recebo o erro "invalid_grant"
O dados postados são:
client_id=xxxxxx&client_secret=yyyyy&code=zzzzz&grant_type= authorization_code&redirect_uri=minha_uri
Obviamente, por razoes de seguranca, omiti os dados verdadeiros.

A sub que busca o Token é a mesma do exemplo em C#:
```
public void GetAccessToken( string code, string country )
        {
            this.Country = country;
            SageOneWebRequest request = new SageOneWebRequest();
            _code = code;
            
            string postData = AccessTokenPostData;
            Uri accesstokenURI = new Uri(AccessTokenURL);
            string response = request.PostData(accesstokenURI, postData, "", "", "");
            
            if (response.Length > 0)
            {
                JObject jObject = JObject.Parse(response);
                string access_token = (string) jObject["access_token"];
                string site_id = (string)jObject["resource_owner_id"];

                if (access_token != null)
                {
                    this.Token = access_token;
                }

                if (site_id != null)
                {
                    this.SiteID = site_id;
                }
            }
        }
```
A URL que estou usando é: https://api.sageone.com/oauth2/token
O que está retornando é o seguinte JSON:
{""error"":""invalid_grant""}

Já tentei rodar local e no servidor, e recebo sempre o mesmo erro.
Tambem ja tentei trocar o grant_type por refresh_token e nada.

Alguem pode me ajudar?

**Comment by rodrigoamuchastegui** [comment]
Ninguem da Sageone para responder isto?
Comprei a licença unica e exclusivamente por causa da API e não recebo suporte!

**Comment by mandakeru** [comment]
Olá @rodrigoamuchastegui , desculpe a demora em lhe responder.
Poderia informar qual endpoint esta tentando usar com esse POST?

**Comment by rodrigoamuchastegui** [comment]
Está no meu post inicial @mandakeru 
A URL que estou usando é: https://api.sageone.com/oauth2/token

**Comment by mandakeru** [comment]
Bom dia @rodrigoamuchastegui temos nossa wiki https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki , no final dela depois dos links para os exemplos de cada  linguagem, existe uma explicação de como gerar o token, ela diz assim:

a url usada deve ser  https://app.br.sageone.com/oauth2/auth?client_id=aaxxxaagggaaa432eeee&redirect_uri=https%3A%2F%2Fdevs.s1.br%2Fcallback&response_type=code
Onde o client_id é o seu client id e o redirect_uri a url de redirecionamento, fazendo isso vai abrir uma tela no sage one para que voce autorize sua aplicação a usar sua conta do sage one, depois de autorizar o token aparecerá na url de redirecionamento depois de code=.

**Comment by rodrigoamuchastegui** [comment]
@mandakeru acho que você não leu, novamente, meu post com atenção.
Essa URL que voce mencionou me retorna apenas o AUTHORIZATION CODE, que é utilizado para então, posteriormente, requisitar o ACCESS TOKEN.
O Authorization_Code eu já consegui pegar.  Por favor, leia meu post com atenção.
O que eu preciso agora é do TOKEN.
Pelo menos na documentação, que está em inglês, neste link abaixo, diz que para fazer requisições na API eu preciso do Access Token e não do Authorization Code.

Documentação: https://developers.sageone.com/docs/en/v1#signing_your_requests

Por favor, preciso disto com URGENCIA.

**Comment by mandakeru** [comment]
@rodrigoamuchastegui pode usar o exemplo desse link
https://github.com/Sage/sageone_api_csharp_sample/blob/master/Sage%20One%20Authorisation%20Client/SageOneOAuth.cs

**Comment by mandakeru** [comment]
Olá @rodrigoamuchastegui  verificando melhor seu caso, pude verificar o seguinte:
Para gerar o authorization_code voce passa:
client_id=4b64axxxxxxxxxx00710&
client_secret=iNumzTxxxxxxxxxxhVHstrqWesH8tm9&
code=12a0f9c12cxxxxxxxxxxxxxxx92a48cc1f237ead&
grant_type=authorization_code&
redirect_uri=https://myapp.com/auth/callback

Então a resposta é a seguinte:
{
  "access_token": "cULSIjxxxxxIhbgbjX0R6MkKO",
  "scope": "full_access",
  "token_type": "Bearer",
  "expires_in": 86400,
  "refresh_token": "b06b13xxxxxa275f08bfb57a3"
}
com isso ele ganhou acesso e tem o token

a próxima chamada deve ser a seguinte:
https://www.sageone.com/oauth2/auth?response_type=code&client_id=4b64axxxxxxxxxx00710&redirect_uri=https://myapp.com/auth/callback   &scope=full_access

o scope é importante ser passado também.

Veja se esta fazendo dessa forma e se está usando o scope=full_access.

**Comment by rodrigoamuchastegui** [comment]
Incrivelmente, voces nao leram minha mensgem DE NOVO!
Voce me passou as instrucoes exatamtente como eu disse que fiz no meu primeiro post.
Será que poderiam ler com atenção?  Isto está ficando desgastante.

EU estou passando exatamente estes parametros...
Gostaria de saber, porque estou recebendo esta resposta do servidor de voces ao tentar gerar o Access Token: invalid_grant  ???

Estou copiando e colando o texto que coloquei na minha primeira mensagem:
**O dados postados são:
client_id=xxxxxx&
client_secret=yyyyy&
code=zzzzz&
grant_type= authorization_code&
redirect_uri=minha_uri

Obviamente, por razoes de seguranca, omiti os dados verdadeiros.**

Seu texto abaixo copiando de sua ultima mensagem:
**Para gerar o authorization_code voce passa:
client_id=4b64axxxxxxxxxx00710&
client_secret=iNumzTxxxxxxxxxxhVHstrqWesH8tm9&
code=12a0f9c12cxxxxxxxxxxxxxxx92a48cc1f237ead&
grant_type=authorization_code&
redirect_uri=https://myapp.com/auth/callback**

**Comment by mandakeru** [comment]
Olá @rodrigoamuchastegui eu tinha citado novamente o processo de gerar o authorization code por que esse erro de invalid_grant se da ao informar o código incorreto, por favor verifique se esta informando corretamente os seus dados, como client_id e client_secret, peço também para que gere um novo authorization code, e enfatizo novamente que o erro da sua pergunta(invalid grant) se dá ao fato do authorization code estar invalido.

**Comment by Tarcisiosk** [comment]
https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/23
