### ISSUE TITLE
Erro ao emitir uma NFS-e - PHP

### ISSUE THREAD

**Issue by sandrocavalcanti** [Sage/sageone_br_nfe_documentacao_api#34]
Olá, não estamos conseguindo emitir uma nota pela API.
Realizamos a autenticação via OAuth2 com sucesso, mas, mesmo utilizando o sample em PHP ele retorna erro de autenticação ao requisitar o end point da emissão da nota. 

Alguém poderia nos ajudar?

**Comment by Tarcisiosk** [comment]
Olá @sandrocavalcanti o erro apresentado é `AuthorizationFailure`?

**Comment by sandrocavalcanti** [comment]
Olá Tarcísio, boa tarde.

Amigo, já faz tanto tempo que enviei esse chamado que nem lembro mais do
que se trata.
Na verdade já cancelamos nossa assinatura com o SageOne porque não nos
atendeu.
Obrigado.

Att,

Sandro Cavalcanti

**Comment by zoqui** [comment]
erro na autorização de assinatura é descrito em diversos tickets no github como pode ver:

https://github.com/Sage/sageone_br_nfe_documentacao_api/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Access%20Denied%20


Há alguma coisa que eu ou a comunidade possamos fazer para ajudar?

Eu realmente gostaria de começar a utilizar a api integrada aos nossos sistema mas a falta de suporte adequado traz muito receio de utiliza-la em produção.

**Comment by Tarcisiosk** [comment]
Fechando esse tópico para tratar o caso no #36
