### ISSUE TITLE
POST /notafiscal/v1/nfes/authorize não funciona

### ISSUE THREAD

**Issue by raphaelnm** [Sage/sageone_br_nfe_documentacao_api#35]
Na documentação da API existe uma nota há alguns meses:

> Para criar e emitir uma NFe
> 
> Utilize os mesmos parâmetros, mas use esta URL:
> 
> POST /notafiscal/v1/nfes/authorize
> 
> BUGs conhecidos:
> 
> A emissão de NFes contém uma falha causada por uma alteração recente no fluxo de execução, resultando na falta de assinatura de uma nota antes de ser enviada à SEFAZ. Este erro provavelmente ocorre também na emissão de NFCes.

Essa URL realmente retorna um erro:

```
{
  "success":false,
  "errors":[
    "A Nota Fiscal deve ser Nova.",
    "Vers\u00e3o do XML n\u00e3o encontrada"
   ],
  "url":"http:\/\/app.br.sageone.com\/notafiscal\/incoming_nfes\/4179****"
}
```

A NF é criada como rascunho, mas não é emitida.

**Comment by Tarcisiosk** [comment]
Olá Raphael, nos desculpe pelo transtorno, o antigo analista que estava cuidando do seu caso não está mais na equipe por isso estamos no momento de planning para corrigir o bug que estamos tendo na autorização, avisaremos, assim que possível, a data de liberação dessa correção.

**Comment by raphaelnm** [comment]
Bom dia Tarcisio,

Ok. Obrigado.

**Comment by raphaelnm** [comment]
Alguma novidade, Tarcisio?

**Comment by Tarcisiosk** [comment]
Olá Raphael, ela entrou na nossa sprint de desenvolvimento, a data de publicação prevista é dia 29/06.

**Comment by raphaelnm** [comment]
Obrigado pelo retorno, Tarcisio.

**Comment by raphaelnm** [comment]
Tarcisio, reparei que houve uma alteração no sistema. Testei a correção que vocês supostamente fariam e, como era de se esperar, continua não funcionando. Incrível…

**Comment by Tarcisiosk** [comment]
Olá @raphaelnm tivemos um atraso na versão devido a um update no sistema, o quanto antes irei passar por aqui a data correta que entrará esta correção, mas não passará de semana que vem! Desculpe pelo inconveniente!

**Comment by Tarcisiosk** [comment]
Olá @raphaelnm esta sexta feira irá ao ar a versão com essa correção! Desculpe a demora na resposta :)

**Comment by raphaelnm** [comment]
@Tarcisiosk reparei que as NF não estão sendo autorizadas. Quando acesso o menu "Notas de Produtos" -> "Saídas", todas as notas aparecem como "Autorizando" e não como "Autorizada".

Além disso, quando clico no botão "Gerar arquivo de notas por período" nenhuma nota é exportada.

![captura de tela 2017-09-25 as 17 00 23](https://user-images.githubusercontent.com/10108308/30828324-ace904b2-a213-11e7-91a7-a33d5cdb4d2f.png)

**Comment by Tarcisiosk** [comment]
Fechando este tópico para tratar pelo: https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/37
