### ISSUE TITLE
Essa biblioteca está sendo atualizada?

### ISSUE THREAD

**Issue by djgoulart** [Sage/sageone_br_nfe_documentacao_api#38]
Ao ler a wiki percebi que algumas páginas não recebem atualização há muito tempo. Principalmente com relação à correção de bugs e implementação de novas features.

Tenho interesse em fazer a integração do sistema da minha empresa com a api do sage one, mas fiquei meio desanimado quanto às possibilidades atualmente documentadas.

**Comment by rmomogi** [comment]
Prezado,
Pretendemos atualizar a wiki em breve para facilitar a utilização da API e de seus recursos.

Equipe Sage NFe Dev
