### ISSUE TITLE
Erro ao emitir NFe

### ISSUE THREAD

**Issue by aramisf** [Sage/sageone_br_nfe_documentacao_api#4]
Ao tentar emitir uma NFe, seguindo as [indicações da documentação](https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe), foi reportado o seguinte erro no retorno da API:
```
"success" => false
  "errors" => array:2 [
    0 => "A Nota Fiscal deve ser Nova."
    1 => "Versão do XML não encontrada"
  ]
```

**Comment by raphaelnm** [comment]
@aramisf alguma previsão para a correção desse bug?

**Comment by luizhpcamargo** [comment]
Estamos em vias de corrigir este bug, precisamos esclarecer alguns pontos. Por favor informe algum meio de contato e sua disponibilidade

**Comment by raphaelnm** [comment]
@luizhpcamargo por favor, envie um email para raphael@phosfato.com.br

**Comment by raphaelnm** [comment]
@luizhpcamargo alguma novidade sobre a correção desse bug? A existência da API não faz muito sentido se após a criação da NFe ainda é necessário uma ação manual para transmití-la.

**Comment by luizhpcamargo** [comment]
Liberada a correção em 25/08

**Comment by raphaelnm** [comment]
Eu ainda não consigo utilizar o endpoint: POST /notafiscal/v1/nfes/authorize
A API ainda retorna o mesmo erro e somente cria o rascunho da NFe.
