### ISSUE TITLE
Problemas com post de produtos

### ISSUE THREAD

**Issue by LucasArgate** [Sage/sageone_br_nfe_documentacao_api#40]
Olá pessoal tudo bem?

estou integrando uma empresa a SageOne para emissão de notas fiscais e preciso fazer post de produtos (create new product) e estou seguindo a API v1 conforte esta **[documentação](https://developer.sageone.com/docs/en/v1)**.

Tive sucesso com a autenticação de autorização tranquilo, consegui pegar o access token normal, consegui listar produtos normal.

Porém, quando vou postar um produto novo o servidor retorna o seguinte erro sem especificações:
**O servidor remoto retornou um erro: (405) Método Não Permitido.**

Estou utilizando a bilblioteca de C#, e estou fazendo o request da seguinte maneira:

```

SageOneWebRequest request = new SageOneWebRequest();            
var data = new List<KeyValuePair<string, string>>();
 data.Add(new KeyValuePair<string, string>("description", "Produto teste"));
data.Add(new KeyValuePair<string, string>("sales_price_includes_tax", "false"));
data.Add(new KeyValuePair<string, string>("ledger_account_id", "438"));
 data.Add(new KeyValuePair<string, string>("product_code", "NEWPROD"));
data.Add(new KeyValuePair<string, string>("last_cost_price", "64.95"));
 data.Add(new KeyValuePair<string, string>("sales_price", "99.99"));

var url = new Uri("https://api.sageone.com/accounts/v1/products");     
    
 string resultPost = request.PostData(url, data, "XXXXXXXX", "XXXXXXXXXXXXXXXX");

```

o que será que estou fazendo de errado?

Desde já grato a todos,
Argate

**Comment by Tarcisiosk** [comment]
Olá @LucasArgate, tudo certo e com você?

Infelizmente apenas chamadas GET estão liberadas para os produtos. Você pode criar os produtos  passando os atributos pela criação da nota, dessa forma ele vai criar ou atualizar algum ja existente baseado no ID passado.

O exemplo de como passar os atributos pode ser encontrado na pagina da [NFE](https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe), na parte dos items.

Obrigado!

**Comment by LucasArgate** [comment]
@Tarcisiosk 
Como diferencio nota de produto e de serviço?

Obrigado!

**Comment by guilhermekbral** [comment]
Boa tarde @LucasArgate.

Os endpoints de NF-e e NFS-e são diferentes. Seguem links para a documentação de cada uma delas.
NF-e: https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe
NFS-e: https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFSe

Caso não seja essa a dúvida, peço a gentileza que detalhe um pouco mais a situação para que eu possa lhe auxiliar! :)

**Comment by LucasArgate** [comment]
@guilhermekbral 
muito obrigado por responder, consegui fazer a integração com sucesso!

Só houve alguns problemas na hora de create/athenticate user ma tela de permitir.

Fluxo mapeado:

1. clica no Link para Autorização.
2. clica em "Criar Conta"
3. preencho meus dados ou clico para cadastrar com o Google.
4. cria meu usuário e redireciona para o painel da SageOne 
5. não volta para minha aplicação.

único problema foi isso. De resto fico legal 👍 

Musicalmente,
Argate
