### ISSUE TITLE
Documentação Incompleta da API:

### ISSUE THREAD

**Issue by xvanlima** [Sage/sageone_br_nfe_documentacao_api#42]
Preciso da documentação para:
-  além de criar a nota como rascunho também emitir a nota.
-  pegar o código gerado ao emitir uma nota
-  pegar o pdf da nota gerada

**Comment by xvanlima** [comment]
Como funciona a integração com o google drive?
https://app.br.sageone.com/notafiscal/configurations/google_drive

**Comment by guilhermekbral** [comment]
Boa tarde,

Temos uma página em nossa wiki referente a NF-e, onde existe o endpoint para criação de nota rascunho e autorização da mesma. A wiki pode ser consultada [aqui](https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe#para-criar-e-emitir-uma-nfe)

Referente a dúvida sobre o código, poderia explicar melhor o código a que se refere? Seria a chave de acesso da nota?

O PDF a que se refere é a DANFE da nota? Caso sim, atualmente a API não está preparada para retornar o PDF da danfe da nota fiscal.

A integração com o google drive irá gerar o xml e o html da danfe das notas emitidas no Sage NF-e na pasta indicada para a integração.

**Comment by xvanlima** [comment]
API de emissão. .. é retorno tudo via php mesmo.

Quero não apenas colocar em rascunho mas também emitir..  cancelar. .. e
ter a confirmação do envio da nota tudo via api

Em Ter, 22 de mai de 2018 17:31, Guilherme Cabral Vannuchi <
notifications@github.com> escreveu:

**Comment by guilhermekbral** [comment]
Boa tarde,

Não consegui compreender a dúvida. A criação de nota rascunho e autorização da mesma pode ser efetuada conforme nossa wiki, onde é indicado o endpoint para criação da nota e para autorização da mesma, detalhando os parâmetros aceitos. (Acesse a wiki [aqui](https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe#para-criar-e-emitir-uma-nfe))
Atualmente não é possível cancelar a nota via API. 
Referente a confirmação do envio, por gentileza detalhar melhor a que confirmação está se referindo.

**Comment by xvanlima** [comment]
Isso apenas cria um rascunho para depois ser preciso entrar no sistema e
emitir a nota por lá...

Quero funções via api para emitir, gerar o pdf, cancelar... em fim... tudo
via api
-- Att,
Ivan Xavier Araújo de Lima
Lattes <http://lattes.cnpq.br/7595550329064341>-LinkedIn
<http://www.linkedin.com/profile/view?id=51316386&locale=pt_br&trk=prof-0-ovw-view-secondary>
-Facebook <http://www.facebook.com/ivanxavierlima>
_.: Analista de TI - UFT :.__
- MSc. Computação - UFF-
--- Doutorando PUC-RIO ---
__ +55 63 8121 0234___

**Comment by mawillian** [comment]
Bom dia,

Atualmente só é possível criar o rascunho e realizar a autorização.(Segue [link da Wik](https://github.com/Sage/sageone_br_nfe_documentacao_api/wiki/NFe#para-criar-e-emitir-uma-nfe))
Não é possível gerar o PDF da DANFE e efetuar eventos na NF-e (Cancelamento, carta de correção)

Att,
