### ISSUE TITLE
getAccessToken erro 400 Bad Request

### ISSUE THREAD

**Issue by Biscuri** [Sage/sageone_br_nfe_documentacao_api#44]
Quando eu tento pegar o access token depois de pegar o code, me dá essa exceção:

`file_get_contents(https://api.sageone.com/oauth2/token/): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request`

Onde file_get_contents é a linha 123 do arquivo sageone_client.php, dentro do método getToken.

O post é mandado para: https://api.sageone.com/oauth2/token/

Com esses parâmetros:

`"http" => array:3 [`
`"header" => "Content-type: application/x-www-form-urlencoded\r\n"`
`"method" => "POST"`
`"content" => "client_id=CLIENT_ID&client_secret=CLIENT_SECRET&code=MY_CODE&grant_type=authorization_code&redirect_uri=MY_URI"`
`]`

Onde CLIENT_ID, CLIENT_SECRET e MY_URI são respectivamente copiados dos parâmetros da aplicação, e MY_CODE é o parâmetro code do callback.

Por que estava funcionando e de repente me dá erro 400 de novo? Eu não mudei nada dos campos da aplicação, nem nenhuma configuração da conta da Sage.

**Comment by mawillian** [comment]
Bom dia,

 Poderia me informar por gentileza qual foi a última que o processo foi realizado com sucesso?
 Provavelmente a autorização expirou, realize novamente o processo de autorização por gentileza.

Att,
