### ISSUE TITLE
URGENTE: Erro no getAccessToken. Problema na obtenção do Token, gerando o erro invalid_grant ou vazio

### ISSUE THREAD

**Issue by kmapps** [Sage/sageone_br_nfe_documentacao_api#50]
Bom dia pessoal,
Está acontecendo a mesma coisa conosco.
Quando vamos utilizar o método getAccessToken para gerar o token dá erro.
Retorna vazio ou {"error":"invalid_grant"}
Também já utilizamos as duas opções informadas: authorization_code e refresh_token.
Por favor, precisamos de orientação para resolver isso de forma urgente.

Estamos com os mesmo problemas relatados abaixo:
https://github.com/Sage/sageone_br_nfe_documentacao_api/issues/36

Já testamos com todos os endpoints relatados no link acima.
Não estamos conseguindo gerar o token e por isso não conseguimos gerar as notas fiscais.
Estamos utilizando a biblioteca PHP de vocês e mesmo assim não fuciona https://github.com/Sage/sageone_api_php_sample

Obrigado.

**Comment by rmomogi** [comment]
Prezado @kmapps, a colaborada Ana da equipe comercial contatará para obter as informações do acesso para validarmos o caso.

Obrigado,
Equipe Dev Sage NFe

**Comment by rmomogi** [comment]
Após a avaliação sugiro sempre verificar:

- O callback (redirect_uri) está igual ao que foi preenchido no cadastro da aplicação em [https://developers.sageone.com/applications](https://developers.sageone.com/applications)
- O code de retorno após a autorização esta sendo usado corretamente
- Não permitir que ao receber o code após a autorização passe o tempo de 1 minuto para geração do token
